2020-06-05 13:07:38,293 ERROR 18424 nodejs.ClusterClientNoResponseError: client no response in 869459ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18424
hostname: lanjianhuas-MacBook-Pro.local

2020-06-05 14:03:33,939 ERROR 18424 nodejs.ClusterClientNoResponseError: client no response in 274977ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18424
hostname: lanjianhuas-MacBook-Pro.local

2020-06-05 15:43:08,001 ERROR 18424 nodejs.ClusterClientNoResponseError: client no response in 213058ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18424
hostname: lanjianhuas-MacBook-Pro.local

2020-06-06 15:07:14,055 ERROR 82960 [egg-mongoose] mongodb://127.0.0.1/blog disconnected
2020-06-06 15:07:14,060 ERROR 82960 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:561:14
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:994:11
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 82960
hostname: jianhuadeMacBook-Pro.local

2020-06-06 15:07:14,060 ERROR 82960 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:561:14
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:994:11
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 82960
hostname: jianhuadeMacBook-Pro.local

2020-06-06 15:07:14,062 ERROR 82960 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:561:14
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/pool.js:994:11
    at /Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_mongodb@3.5.5@mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
name: "MongoNetworkError"
pid: 82960
hostname: jianhuadeMacBook-Pro.local

2020-06-07 12:32:17,889 ERROR 712 nodejs.ClusterClientNoResponseError: client no response in 2027534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 712
hostname: MacBook-Pro.local

2020-06-07 13:59:09,546 ERROR 712 nodejs.ClusterClientNoResponseError: client no response in 5171677ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 712
hostname: MacBook-Pro.local

2020-06-15 12:48:20,786 ERROR 78022 nodejs.ClusterClientNoResponseError: client no response in 103726ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78022
hostname: MacBook-Pro.local

2020-06-15 12:50:54,613 ERROR 78022 nodejs.ClusterClientNoResponseError: client no response in 113805ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78022
hostname: MacBook-Pro.local

2020-06-15 12:52:47,411 ERROR 78022 nodejs.ClusterClientNoResponseError: client no response in 92774ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78022
hostname: MacBook-Pro.local

2020-06-15 13:00:45,347 ERROR 78022 nodejs.ClusterClientNoResponseError: client no response in 373849ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78022
hostname: MacBook-Pro.local

2020-06-15 13:07:39,877 ERROR 78022 nodejs.ClusterClientNoResponseError: client no response in 374515ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78022
hostname: MacBook-Pro.local

2020-06-15 19:11:24,738 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 323724ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-15 19:59:44,610 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 2899863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-16 02:13:33,227 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 7265709ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-16 07:55:09,617 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 20495857ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-16 07:58:40,551 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 103424ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

2020-06-16 08:23:26,650 ERROR 78875 nodejs.ClusterClientNoResponseError: client no response in 105861ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lanjianhua/Desktop/lanjianhua/service/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 78875
hostname: MacBook-Pro.local

